# Generated by Django 3.0.6 on 2020-05-07 06:12

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_type', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['vendor_type'],
            },
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=500)),
                ('veg_price', models.FloatField()),
                ('non_veg_price', models.FloatField()),
                ('maximum', django_mysql.models.ListCharField(models.IntegerField(), max_length=10, size=None)),
                ('minimum', django_mysql.models.ListCharField(models.IntegerField(), max_length=10, size=None)),
                ('address', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=20)),
                ('about', models.CharField(max_length=500)),
                ('highlights', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.City')),
                ('vendor_type', models.ManyToManyField(to='hotels.VendorType')),
            ],
        ),
    ]
